In [1]:
import pandas as pd

In [2]:
import os

# create folder for raw data
os.makedirs("Data/raw", exist_ok=True)

# Download only the october dataset
!kaggle datasets download -d mkechinov/ecommerce-behavior-data-from-multi-category-store -f 2019-Oct.csv -p data/raw

# Confirm
os.listdir("Data/raw")

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.2.1), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/mkechinov/ecommerce-behavior-data-from-multi-category-store
License(s): copyright-authors
2019-Oct.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

['2019-Oct.csv', '2019-Oct.csv.zip']

In [4]:
import zipfile

with zipfile.ZipFile("Data/raw/2019-Oct.csv.zip", 'r') as zip_ref:
    zip_ref.extractall("Data/raw")


os.remove("Data/raw/2019-Oct.csv.zip")
os.listdir("Data/raw")

FileNotFoundError: [Errno 2] No such file or directory: 'Data/raw/2019-Oct.csv.zip'

In [6]:
ecommerce_data = pd.read_csv("Data/raw/2019-Oct.csv", nrows=100000)
ecommerce_data.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [11]:
ecommerce_data.describe()

         product_id   category_id          price       user_id
count  1.000000e+05  1.000000e+05  100000.000000  1.000000e+05
mean   1.029819e+07  2.056094e+18     286.827664  5.310909e+08
std    1.113546e+07  1.490982e+16     360.304691  1.662030e+07
min    1.001588e+06  2.053014e+18       0.000000  3.064418e+08
25%    1.005124e+06  2.053014e+18      61.010000  5.156360e+08
50%    5.100580e+06  2.053014e+18     154.380000  5.269649e+08
75%    1.590169e+07  2.053014e+18     357.110000  5.477189e+08
max    5.310002e+07  2.175420e+18    2574.070000  5.554835e+08

In [9]:
ecommerce_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   event_time     100000 non-null  str
 1   event_type     100000 non-null  str
 2   product_id     100000 non-null  int64
 3   category_id    100000 non-null  int64
 4   category_code  67413 non-null   str
 5   brand          85607 non-null   str
 6   price          100000 non-null  float64
 7   user_id        100000 non-null  int64
 8   user_session   100000 non-null  str
dtypes: float64(1), int64(3), str(5)
memory usage: 6.9 MB

In [ ]:
e