In [1]:
import pandas as pd

In [2]:
import os

# create folder for raw data
os.makedirs("Data/raw", exist_ok=True)

# Download only the october dataset
!kaggle datasets download -d mkechinov/ecommerce-behavior-data-from-multi-category-store -f 2019-Oct.csv -p data/raw

# Confirm
os.listdir("Data/raw")

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.2.1), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/mkechinov/ecommerce-behavior-data-from-multi-category-store
License(s): copyright-authors
2019-Oct.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

['2019-Oct.csv', '2019-Oct.csv.zip']

In [4]:
import zipfile

with zipfile.ZipFile("Data/raw/2019-Oct.csv.zip", 'r') as zip_ref:
    zip_ref.extractall("Data/raw")


os.remove("Data/raw/2019-Oct.csv.zip")
os.listdir("Data/raw")

FileNotFoundError: [Errno 2] No such file or directory: 'Data/raw/2019-Oct.csv.zip'

In [6]:
ecommerce_data = pd.read_csv("Data/raw/2019-Oct.csv", nrows=100000)
ecommerce_data.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [11]:
ecommerce_data.describe()

         product_id   category_id          price       user_id
count  1.000000e+05  1.000000e+05  100000.000000  1.000000e+05
mean   1.029819e+07  2.056094e+18     286.827664  5.310909e+08
std    1.113546e+07  1.490982e+16     360.304691  1.662030e+07
min    1.001588e+06  2.053014e+18       0.000000  3.064418e+08
25%    1.005124e+06  2.053014e+18      61.010000  5.156360e+08
50%    5.100580e+06  2.053014e+18     154.380000  5.269649e+08
75%    1.590169e+07  2.053014e+18     357.110000  5.477189e+08
max    5.310002e+07  2.175420e+18    2574.070000  5.554835e+08

In [9]:
ecommerce_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   event_time     100000 non-null  str
 1   event_type     100000 non-null  str
 2   product_id     100000 non-null  int64
 3   category_id    100000 non-null  int64
 4   category_code  67413 non-null   str
 5   brand          85607 non-null   str
 6   price          100000 non-null  float64
 7   user_id        100000 non-null  int64
 8   user_session   100000 non-null  str
dtypes: float64(1), int64(3), str(5)
memory usage: 6.9 MB

In [15]:
ecommerce_data['event_time']= pd.to_datetime(ecommerce_data['event_time'])

In [16]:
ecommerce_data['event_time']

0       2019-10-01 00:00:00+00:00
1       2019-10-01 00:00:00+00:00
2       2019-10-01 00:00:01+00:00
3       2019-10-01 00:00:01+00:00
4       2019-10-01 00:00:04+00:00
                   ...
99995   2019-10-01 04:28:27+00:00
99996   2019-10-01 04:28:27+00:00
99997   2019-10-01 04:28:27+00:00
99998   2019-10-01 04:28:27+00:00
99999   2019-10-01 04:28:27+00:00
Name: event_time, Length: 100000, dtype: datetime64[us, UTC]

In [18]:
ecommerce_data['event_type'].value_counts()

event_type
view        97130
purchase     1655
cart         1215
Name: count, dtype: int64

In [26]:
ecommerce_data['price'].eq(0).sum()

np.int64(119)

In [28]:
ecommerce_data[ecommerce_data['price']==0]['event_type'].value_counts()

event_type
view    119
Name: count, dtype: int64

In [29]:
ecommerce_data.duplicated().sum()

np.int64(17)

In [30]:
print("Minimum:", ecommerce_data['event_time'].min())
print("Maximum:", ecommerce_data['event_time'].max())

Minimum: 2019-10-01 00:00:00+00:00
Maximum: 2019-10-01 04:28:27+00:00

In [32]:
sample_chunks = []

chunk_size = 500000

chunk_reader =pd.read_csv("Data/raw/2019-Oct.csv", chunksize=chunk_size)

for i, chunk in enumerate(chunk_reader):
    print(f"Processing chunk {i}: shape is {chunk.shape}")
    chunk_sample = chunk.sample(n=10000, random_state=42)
    sample_chunks.append(chunk_sample)


ecommerce_sample = pd.concat(sample_chunks, ignore_index = True)
print("Final sample shape:", ecommerce_sample.shape)

Processing chunk 0: shape is (500000, 9)
Processing chunk 1: shape is (500000, 9)
Processing chunk 2: shape is (500000, 9)
Processing chunk 3: shape is (500000, 9)
Processing chunk 4: shape is (500000, 9)
Processing chunk 5: shape is (500000, 9)
Processing chunk 6: shape is (500000, 9)
Processing chunk 7: shape is (500000, 9)
Processing chunk 8: shape is (500000, 9)
Processing chunk 9: shape is (500000, 9)
Processing chunk 10: shape is (500000, 9)
Processing chunk 11: shape is (500000, 9)
Processing chunk 12: shape is (500000, 9)
Processing chunk 13: shape is (500000, 9)
Processing chunk 14: shape is (500000, 9)
Processing chunk 15: shape is (500000, 9)
Processing chunk 16: shape is (500000, 9)
Processing chunk 17: shape is (500000, 9)
Processing chunk 18: shape is (500000, 9)
Processing chunk 19: shape is (500000, 9)
Processing chunk 20: shape is (500000, 9)
Processing chunk 21: shape is (500000, 9)
Processing chunk 22: shape is (500000, 9)
Processing chunk 23: shape is (500000, 9)
Processing chunk 24: shape is (500000, 9)
Processing chunk 25: shape is (500000, 9)
Processing chunk 26: shape is (500000, 9)
Processing chunk 27: shape is (500000, 9)
Processing chunk 28: shape is (500000, 9)
Processing chunk 29: shape is (500000, 9)
Processing chunk 30: shape is (500000, 9)
Processing chunk 31: shape is (500000, 9)
Processing chunk 32: shape is (500000, 9)
Processing chunk 33: shape is (500000, 9)
Processing chunk 34: shape is (500000, 9)
Processing chunk 35: shape is (500000, 9)
Processing chunk 36: shape is (500000, 9)
Processing chunk 37: shape is (500000, 9)
Processing chunk 38: shape is (500000, 9)
Processing chunk 39: shape is (500000, 9)
Processing chunk 40: shape is (500000, 9)
Processing chunk 41: shape is (500000, 9)
Processing chunk 42: shape is (500000, 9)
Processing chunk 43: shape is (500000, 9)
Processing chunk 44: shape is (500000, 9)
Processing chunk 45: shape is (500000, 9)
Processing chunk 46: shape is (500000, 9)
Processing chunk 47: shape is (500000, 9)
Processing chunk 48: shape is (500000, 9)
Processing chunk 49: shape is (500000, 9)
Processing chunk 50: shape is (500000, 9)
Processing chunk 51: shape is (500000, 9)
Processing chunk 52: shape is (500000, 9)
Processing chunk 53: shape is (500000, 9)
Processing chunk 54: shape is (500000, 9)
Processing chunk 55: shape is (500000, 9)
Processing chunk 56: shape is (500000, 9)
Processing chunk 57: shape is (500000, 9)
Processing chunk 58: shape is (500000, 9)
Processing chunk 59: shape is (500000, 9)
Processing chunk 60: shape is (500000, 9)
Processing chunk 61: shape is (500000, 9)
Processing chunk 62: shape is (500000, 9)
Processing chunk 63: shape is (500000, 9)
Processing chunk 64: shape is (500000, 9)
Processing chunk 65: shape is (500000, 9)
Processing chunk 66: shape is (500000, 9)
Processing chunk 67: shape is (500000, 9)
Processing chunk 68: shape is (500000, 9)
Processing chunk 69: shape is (500000, 9)
Processing chunk 70: shape is (500000, 9)
Processing chunk 71: shape is (500000, 9)
Processing chunk 72: shape is (500000, 9)
Processing chunk 73: shape is (500000, 9)
Processing chunk 74: shape is (500000, 9)
Processing chunk 75: shape is (500000, 9)
Processing chunk 76: shape is (500000, 9)
Processing chunk 77: shape is (500000, 9)
Processing chunk 78: shape is (500000, 9)
Processing chunk 79: shape is (500000, 9)
Processing chunk 80: shape is (500000, 9)
Processing chunk 81: shape is (500000, 9)
Processing chunk 82: shape is (500000, 9)
Processing chunk 83: shape is (500000, 9)
Processing chunk 84: shape is (448764, 9)
Final sample shape: (850000, 9)

In [33]:
ecommerce_sample.to_csv("Data/raw/sample_oct_850k.csv", index=False)

In [34]:
ecommerce_sample.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 04:32:52 UTC,view,12719453,2053013553559896355,NaN,matador,397.44,517886245,7d1528ae-8dfa-4c97-ab4c-974815b9f431
1,2019-10-01 06:06:39 UTC,view,10900328,2053013555069845885,appliances.kitchen.mixer,dauscher,12.84,519282157,55efefd9-53c4-472c-bf6e-45b60ea9ec5a
2,2019-10-01 05:11:34 UTC,view,3100564,2053013555262783879,appliances.kitchen.blender,philips,61.75,539168115,697beb54-e90e-4eeb-8822-eab39935c911
3,2019-10-01 05:04:16 UTC,view,26100001,2053013553887052089,NaN,sulu,25.74,555239099,19041a8f-8a4c-4d6f-934b-3130f33017fe
4,2019-10-01 09:04:19 UTC,view,1306569,2053013558920217191,computers.notebook,acer,1055.11,517726252,1872ffce-39dd-43de-ba53-a49b90281fed

In [36]:
ecommerce_sample.describe()

         product_id   category_id          price       user_id
count  8.500000e+05  8.500000e+05  850000.000000  8.500000e+05
mean   1.054867e+07  2.057422e+18     290.297111  5.335454e+08
std    1.188738e+07  1.849463e+16     357.694568  1.852221e+07
min    1.000978e+06  2.053014e+18       0.000000  1.842654e+08
25%    1.005157e+06  2.053014e+18      65.900000  5.159117e+08
50%    5.000475e+06  2.053014e+18     162.730000  5.296969e+08
75%    1.600030e+07  2.053014e+18     358.570000  5.515866e+08
max    6.050001e+07  2.175420e+18    2574.070000  5.662793e+08

In [37]:
ecommerce_sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 850000 entries, 0 to 849999
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   event_time     850000 non-null  str
 1   event_type     850000 non-null  str
 2   product_id     850000 non-null  int64
 3   category_id    850000 non-null  int64
 4   category_code  579482 non-null  str
 5   brand          727987 non-null  str
 6   price          850000 non-null  float64
 7   user_id        850000 non-null  int64
 8   user_session   850000 non-null  str
dtypes: float64(1), int64(3), str(5)
memory usage: 58.4 MB

In [ ]:
ecommerce_sample['event_time'] = pd.to_datetime